import { dictionaries } from "./src/i18n.js";
const G = "https://www.google.com/maps/search/?api=1&query=Roby%27s+Coffee+House+Gazipasa";
const Y = "https://yandex.com.tr/maps/org/roby_s_coffee_house/194573272549/";
const I = "https://www.instagram.com/robyscoffeehouse/";
const M = "https://www.openstreetmap.org/export/embed.html?bbox=32.2925%2C36.2615%2C32.3037%2C36.2708&layer=mapnik&marker=36.266192%2C32.298118";
const q = (s, r = document) => r.querySelector(s);
const qa = (s, r = document) => Array.from(r.querySelectorAll(s));
const get = (k) => { try { return localStorage.getItem(k); } catch { return null; } };
const set = (k, v) => { try { localStorage.setItem(k, v); } catch {} };
let lang = get("robys-language") === "en" ? "en" : get("robys-language") === "ru" ? "ru" : "tr";
let installPrompt = null;
const t = (k) => dictionaries[lang][k];
function toast(text) { let el = q(".robys-toast"); if (!el) { el = document.createElement("div"); el.className = "robys-toast"; el.role = "status"; document.body.append(el); } el.textContent = text; el.classList.add("is-visible"); setTimeout(() => el?.classList.remove("is-visible"), 2200); }
function setLanguage(next) { lang = next; document.documentElement.lang = next; set("robys-language", next); qa("[data-i18n]").forEach(el => { const k = el.dataset.i18n; if (k) el.textContent = t(k); }); qa("[data-i18n-html]").forEach(el => { const k = el.dataset.i18nHtml; if (k) el.innerHTML = t(k); }); qa(".lang-button").forEach(b => { const on = b.dataset.lang === next; b.classList.toggle("active", on); b.setAttribute("aria-pressed", String(on)); }); live(); passport(); }
function card(n, title, text, drink, icon) { return `<article class="ritual-card reveal"><span class="ritual-number">${n}</span><div class="ritual-icon">${icon}</div><h3 data-i18n="${title}"></h3><p data-i18n="${text}"></p><strong data-i18n="${drink}"></strong><button class="ritual-save" type="button" data-i18n="saveRitual"></button></article>`; }
function inject() {
  const nav = q(".main-nav"); if (nav && !q("a[href='#experience']", nav)) nav.querySelector("a[href='#gallery']")?.insertAdjacentHTML("beforebegin", `<a href="#experience" data-i18n="navExperience"></a>`);
  const menu = q("#menu"); if (menu && !q("#experience")) menu.insertAdjacentHTML("afterend", `<section id="experience" class="world-experience"><div class="container"><div class="world-heading reveal"><div><p class="eyebrow" data-i18n="experienceEyebrow"></p><h2 data-i18n-html="experienceTitle"></h2></div><p data-i18n="experienceText"></p></div><div class="ritual-grid">${card("01","morningTitle","morningText","morningDrink","✦")}${card("02","sunsetTitle","sunsetText","sunsetDrink","☼")}${card("03","slowTitle","slowText","slowDrink","♡")}</div><article class="matcher-banner reveal"><div><span class="matcher-badge" data-i18n="matcherBadge"></span><h3 data-i18n="matcherTitle"></h3><p data-i18n="matcherText"></p></div><button class="button button-primary matcher-open" type="button" data-i18n="startMatcher"></button></article></div></section>`);
  const experience = q("#experience"); if (experience && !q(".story-section")) experience.insertAdjacentHTML("afterend", `<section class="story-section"><div class="container"><div class="world-heading reveal"><div><p class="eyebrow" data-i18n="storiesEyebrow"></p><h2 data-i18n-html="storiesTitle"></h2></div></div><div class="story-rail"><article class="story-card reveal"><img src="${q(".hero-image-wrap img")?.src ?? ""}" alt="Roby's terrace" loading="lazy"><span>01 · TERRACE</span><h3 data-i18n="storyTerrace"></h3></article><article class="story-card reveal"><img src="https://img02.restaurantguru.com/cde4-Restaurant-Robys-Coffee-House-beverage.jpg" alt="Coffee" loading="lazy"><span>02 · COFFEE</span><h3 data-i18n="storyCoffee"></h3></article><article class="story-card reveal"><img src="https://img02.restaurantguru.com/c34f-Restaurant-Robys-Coffee-House-interior.jpg" alt="Interior" loading="lazy"><span>03 · SPACE</span><h3 data-i18n="storyInterior"></h3></article></div></div></section>`);
  injectGallery(); injectReviews(); injectPassport(); injectMap(); injectDock(); injectMatcher();
  const heroMeta = q(".hero-meta"); if (heroMeta && !q(".live-status-card", heroMeta)) heroMeta.insertAdjacentHTML("beforeend", `<div class="live-status-card"><span class="live-status-dot"></span><span><strong data-live-status></strong><small data-crowd-status></small></span></div>`);
}
function injectGallery() { if (q("#gallery")) return; const hero = q(".hero-image-wrap img")?.src ?? ""; const p = [[hero,"terrace","OUTDOOR"],["https://img02.restaurantguru.com/c34f-Restaurant-Robys-Coffee-House-interior.jpg","interior","INTERIOR"],["https://img02.restaurantguru.com/c893-Restaurant-Robys-Coffee-House-food.jpg","food","FOOD"],["https://img02.restaurantguru.com/cde4-Restaurant-Robys-Coffee-House-beverage.jpg","drink","COFFEE"],["https://img02.restaurantguru.com/c188-Restaurant-Robys-Coffee-House-design.jpg","design","DETAILS"]]; q(".quote-section")?.insertAdjacentHTML("beforebegin", `<section id="gallery" class="social-gallery"><div class="container"><div class="gallery-head reveal"><div class="gallery-head-copy"><p class="eyebrow" data-i18n="galleryEyebrow"></p><h2 data-i18n-html="galleryTitle"></h2><p data-i18n="galleryText"></p></div><div class="gallery-source-row"><a class="gallery-source" href="${I}" target="_blank">Instagram ↗</a><a class="gallery-source" href="${G}" target="_blank">Google Maps ↗</a><a class="gallery-source" href="${Y}" target="_blank">Yandex Maps ↗</a></div></div><div class="gallery-grid">${p.map(([src,k,c]) => `<button class="gallery-card reveal" type="button"><img src="${src}" alt="Roby's ${k}" loading="lazy"><span class="gallery-card-caption"><span class="gallery-card-copy"><strong data-i18n="${k}"></strong><span>${c}</span></span><span class="gallery-zoom">↗</span></span></button>`).join("")}</div></div></section>`); }
function injectReviews() { const gallery = q("#gallery"); if (!gallery || q("#reviews")) return; const rows = [["Google","İpek Yıldırım","★★★★★","reviewIpek","reviewIpekMeta",G],["Google","Elena Chkalova","★★★★★","reviewElena","reviewElenaMeta",G],["Yandex","Yandex Maps","★★★★★","reviewYandex","reviewYandexMeta",Y],["Instagram","@robyscoffeehouse","● ● ●","reviewInstagram","reviewInstagramMeta",I]]; gallery.insertAdjacentHTML("afterend", `<section id="reviews" class="guest-reviews"><div class="container reviews-wrap"><div class="reviews-head reveal"><div><p class="eyebrow" data-i18n="reviewsEyebrow"></p><h2 data-i18n-html="reviewsTitle"></h2></div><div class="reviews-summary"><a class="rating-pill" href="${G}" target="_blank"><div class="rating-pill-top"><strong>4.7</strong><span class="rating-stars">★★★★★</span></div><span data-i18n="googleVotes"></span></a><a class="rating-pill" href="${Y}" target="_blank"><div class="rating-pill-top"><strong>4.9</strong><span class="rating-stars">★★★★★</span></div><span data-i18n="yandexRating"></span></a></div></div><div class="reviews-grid">${rows.map(([s,a,r,qk,mk,h]) => `<article class="review-card reveal"><div><div class="review-source"><div class="review-source-left"><span class="review-source-icon">${s === "Instagram" ? "IG" : s[0]}</span><span class="review-source-name"><strong>${a}</strong><span>${s}</span></span></div><span class="review-rating">${r}</span></div><blockquote class="review-quote small" data-i18n="${qk}"></blockquote><p data-i18n="${mk}"></p></div><div class="review-footer"><span>${s}</span><a href="${h}" target="_blank"><span data-i18n="sourceOpen"></span> ↗</a></div></article>`).join("")}</div></div></section>`); }
function injectPassport() { const visit = q("#visit"); if (!visit || q("#my-robys")) return; visit.insertAdjacentHTML("beforebegin", `<section id="my-robys" class="my-robys-section"><div class="container my-robys-grid"><div class="my-robys-copy reveal"><p class="eyebrow" data-i18n="myRobysEyebrow"></p><h2 data-i18n-html="myRobysTitle"></h2><p data-i18n="myRobysText"></p><div class="install-card"><div><strong data-i18n="installTitle"></strong><span data-i18n="installText"></span></div><button class="button button-secondary install-app" type="button" data-i18n="installApp"></button></div></div><div class="passport-card reveal"><div class="passport-top"><span class="passport-brand">R</span><div><strong>MY ROBY'S</strong><small data-i18n="passportLocal"></small></div></div><div class="stamp-grid">${Array.from({length:6},(_,i)=>`<span class="passport-stamp" data-stamp="${i}"><i>☕</i></span>`).join("")}</div><div class="passport-stats"><div><span data-passport-count>0</span><small data-i18n="passportVisits"></small></div><div><span data-i18n="favoriteLabel"></span><strong data-favorite-drink></strong></div></div><button class="button button-primary passport-add" type="button" data-i18n="addVisit"></button></div></div></section>`); }
function injectMap() { const old = q(".map-card"); if (!old || old.classList.contains("real-map")) return; const map = document.createElement("div"); map.className = "map-card real-map reveal"; map.innerHTML = `<div class="map-preview"><button class="map-load-button" type="button"><span class="map-load-icon"><span>R</span></span><strong data-i18n="mapShow"></strong><small data-i18n="mapNote"></small></button></div><div class="map-frame-shell" hidden></div><div class="map-info-panel"><div class="map-address"><span class="map-address-kicker">ROBY'S COFFEE HOUSE</span><strong>Pazarcı Mah., Uğur Mumcu Cad.</strong><small>Gazipaşa / Antalya · 36.266192, 32.298118</small></div><div class="map-route-actions"><a class="map-route-link" href="${G}" target="_blank"><span class="map-route-dot">G</span>Google Maps</a><a class="map-route-link" href="${Y}" target="_blank"><span class="map-route-dot">Y</span>Yandex Maps</a></div></div>`; old.replaceWith(map); }
function injectDock() { if (q(".mobile-dock")) return; document.body.insertAdjacentHTML("beforeend", `<nav class="mobile-dock" aria-label="Quick actions"><a href="#menu"><span>☕</span><small data-i18n="dockMenu"></small></a><button type="button" class="matcher-open"><span>✦</span><small data-i18n="dockMood"></small></button><a href="#my-robys"><span>R</span><small data-i18n="dockMyRobys"></small></a><a href="${G}" target="_blank"><span>⌖</span><small data-i18n="dockRoute"></small></a></nav>`); }
function injectMatcher() { if (q("#coffee-matcher")) return; document.body.insertAdjacentHTML("beforeend", `<dialog id="coffee-matcher" class="world-dialog"><div class="dialog-shell"><button class="dialog-close" type="button">×</button><div class="dialog-progress"><span></span></div><div class="dialog-content"></div></div></dialog>`); }
function matcher() { const d = q("#coffee-matcher"), c = q(".dialog-content", d), p = q(".dialog-progress span", d); let step = 0, temp = "", strength = ""; const choices = (title, values) => `<div class="matcher-step"><p class="eyebrow">ROBY'S MATCH</p><h3>${t(title)}</h3><div class="choice-grid">${values.map(([v,k,i])=>`<button class="choice-card" type="button" data-choice="${v}"><span>${i}</span><strong>${t(k)}</strong></button>`).join("")}</div></div>`; const render = () => { p.style.width = `${Math.min((step+1)*25,100)}%`; if(step===0)c.innerHTML=choices("stepTemperature",[["hot","hot","☕"],["cold","cold","❄"]]); if(step===1)c.innerHTML=choices("stepStrength",[["bold","bold","◆"],["smooth","smooth","◇"]]); if(step===2)c.innerHTML=choices("stepMoment",[["focus","focus","✦"],["social","social","☼"],["treat","treat","♡"]]); }; document.addEventListener("click", e => { if (!e.target.closest(".matcher-open")) return; step=0;temp="";strength="";render();d.showModal(); }); d.addEventListener("click", e => { const el=e.target; if(el===d||el.closest(".dialog-close")){d.close();return;} const b=el.closest("[data-choice]"); if(b){if(step===0)temp=b.dataset.choice??"hot"; else if(step===1)strength=b.dataset.choice??"smooth"; else {const drink=temp==="cold"?(strength==="bold"?"Cold Brew":"Iced Latte"):(strength==="bold"?"Americano":"Cappuccino"); c.innerHTML=`<div class="matcher-result"><span class="result-cup">☕</span><p class="eyebrow">${t("recommendation")}</p><h3>${drink}</h3><div class="result-actions"><button class="button button-primary save-match" data-drink="${drink}">${t("saveFavorite")}</button><button class="button button-secondary restart-match">${t("restart")}</button></div></div>`;step=3;return;}step++;render();} const save=el.closest(".save-match"); if(save){set("robys-favorite",save.dataset.drink??"");toast(t("favoriteSaved"));passport();} if(el.closest(".restart-match")){step=0;render();} }); }
function passport() { const count=Math.max(0,Number(get("robys-passport")||0)); q("[data-passport-count]").textContent=String(count); const fav=q("[data-favorite-drink]"); if(fav)fav.textContent=get("robys-favorite")||t("noFavorite"); qa(".passport-stamp").forEach((s,i)=>s.classList.toggle("is-filled",i<Math.min(count,6))); }
function live() { const hour=Number(new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Istanbul",hour:"2-digit",hour12:false}).format(new Date())); const open=hour>=9; const lively=(hour>=12&&hour<=15)||(hour>=18&&hour<=22); qa("[data-live-status]").forEach(el=>el.textContent=t(open?"openToday":"closedNow")); qa("[data-crowd-status]").forEach(el=>el.textContent=open?`${t(lively?"livelyNow":"quietNow")} · ${t("estimated")}`:"09:00 — 00:00"); }
function interactions() { qa(".lang-button").forEach(b=>b.addEventListener("click",()=>setLanguage(b.dataset.lang||"tr"))); q(".menu-toggle")?.addEventListener("click",()=>document.body.classList.toggle("menu-open")); qa(".ritual-save").forEach(b=>b.addEventListener("click",()=>{const drink=q("strong",b.closest(".ritual-card"))?.textContent??"";set("robys-favorite",drink);b.textContent=t("saved");toast(t("favoriteSaved"));passport();})); q(".passport-add")?.addEventListener("click",()=>{const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());if(get("robys-last-visit")===today){toast(t("visitAlreadyAdded"));return;}set("robys-last-visit",today);set("robys-passport",String(Number(get("robys-passport")||0)+1));passport();toast(t("visitAdded"));}); q(".map-load-button")?.addEventListener("click",()=>{const shell=q(".map-frame-shell"),preview=q(".map-preview");if(shell.childElementCount)return;const f=document.createElement("iframe");f.src=M;f.title=t("mapTitle");f.loading="lazy";shell.append(f);shell.hidden=false;preview.hidden=true;}); window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;}); document.addEventListener("click",async e=>{if(!e.target.closest(".install-app"))return;if(!installPrompt){toast(t("installUnavailable"));return;}await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;}); }
function reveal() { if("IntersectionObserver" in window){const o=new IntersectionObserver((entries,obs)=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add("visible");obs.unobserve(x.target);}}),{threshold:.08,rootMargin:"100px 0px"});qa(".reveal").forEach(el=>o.observe(el));}else qa(".reveal").forEach(el=>el.classList.add("visible")); const progress=document.createElement("div");progress.className="scroll-progress";document.body.prepend(progress);let queued=false;addEventListener("scroll",()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max>0?Math.min(scrollY/max,1):0})`;q(".site-header")?.classList.toggle("scrolled",scrollY>16);queued=false;});},{passive:true}); }
function init() { const y=q("#current-year");if(y)y.textContent=String(new Date().getFullYear()); inject(); interactions(); matcher(); setLanguage(lang); passport(); live(); setInterval(live,60000); reveal(); if("serviceWorker" in navigator&&location.protocol==="https:")addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>undefined),{once:true}); }
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init,{once:true}):init();
