import{menuCategories}from"./menu-catalog.js?v=20260904-premium-order-v1";
import{copy,supportedLanguages}from"./discover-copy.js";
import{journeys,imageAlt}from"./discover-journeys-v2.js";
const S={language:"robys-language",visitDate:"robys-discovery-last-date",visits:"robys-discovery-visits",discovered:"robys-discovery-pairs"};
const el={time:document.querySelector("#time-context"),weather:document.querySelector("#weather-context"),step:document.querySelector("#relationship-step"),stageTitle:document.querySelector("#relationship-title"),stageBody:document.querySelector("#relationship-description"),products:document.querySelector("#pairing-products"),number:document.querySelector("#pairing-number"),kicker:document.querySelector("#pairing-kicker"),name:document.querySelector("#pairing-name"),reason:document.querySelector("#pairing-reason"),menuLink:document.querySelector("#pairing-menu-link"),next:document.querySelector("#next-pairing"),done:document.querySelector("#mark-discovered"),langs:[...document.querySelectorAll(".lang-button")]};
const read=k=>{try{return localStorage.getItem(k)}catch{return null}},write=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
let lang=supportedLanguages.includes(read(S.language))?read(S.language):"tr",time=getTime(),weather="unavailable",current=null,candidates=[],candidateIndex=0,discovered=readSet(),visits=registerVisit(),userInteracted=false;
function local(v){return v?.[lang]??v?.tr??v?.en??""}
function getTime(){const hour=Number(new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Istanbul",hour:"2-digit",hour12:false}).format(new Date()));if(hour>=6&&hour<11)return"morning";if(hour>=11&&hour<17)return"day";if(hour>=17&&hour<22)return"evening";return"late"}
function registerVisit(){const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),stored=Number.parseInt(read(S.visits)||"0",10),next=read(S.visitDate)===today?Math.max(stored,1):stored+1;write(S.visitDate,today);write(S.visits,String(next));return next}
function readSet(){try{const data=JSON.parse(read(S.discovered)||"[]");return new Set(Array.isArray(data)?data.filter(x=>typeof x==="string"):[])}catch{return new Set()}}
function items(category){return category.items??category.groups.flatMap(group=>group.items)}
function findItem(name){for(const category of menuCategories){const item=items(category).find(candidate=>candidate.name.en===name);if(item)return item}return null}
function price(value){return`${new Intl.NumberFormat("tr-TR",{maximumFractionDigits:0}).format(value)} ₺`}
function productView(product){const item=findItem(product.name),portrait=document.createElement("div");portrait.className="product-portrait";if(product.image){const image=document.createElement("img");image.src=product.image;image.alt=local(imageAlt[product.name])||local(item?.name)||product.name;image.loading="eager";image.decoding="async";portrait.append(image)}else{const fallback=document.createElement("span");fallback.className="product-fallback";fallback.setAttribute("aria-hidden","true");fallback.textContent=product.emoji;portrait.append(fallback)}const meta=document.createElement("div"),name=document.createElement("strong"),cost=document.createElement("span");meta.className="product-meta";name.textContent=local(item?.name)||product.name;cost.textContent=item?price(item.price):"";meta.append(name,cost);portrait.append(meta);return portrait}
function stageIndex(){if(visits<=1)return 0;if(visits<=3)return 1;if(visits<=6)return 2;if(visits<=10)return 3;return 4}
function renderStage(){const index=stageIndex(),[title,body]=copy[lang].stages[index];el.step.textContent=String(index+1).padStart(2,"0");el.stageTitle.textContent=title;el.stageBody.textContent=body}
function choose(){const exact=`${time}:${weather}`,exactMatches=journeys.filter(j=>j.contexts.includes(exact)),timeMatches=journeys.filter(j=>j.contexts.some(c=>c.startsWith(`${time}:`))),pool=exactMatches.length?exactMatches:timeMatches.length?timeMatches:journeys,unseen=pool.filter(j=>!discovered.has(j.id)),seen=pool.filter(j=>discovered.has(j.id));candidates=[...unseen,...seen];candidateIndex=0}
function renderJourney(journey){current=journey;el.products.dataset.pairingId=journey.id;el.products.replaceChildren(productView(journey.primary),productView(journey.companion));el.number.textContent=String(journeys.indexOf(journey)+1).padStart(2,"0");el.kicker.textContent=copy[lang].pairingKicker;el.name.textContent=local(journey.title);el.reason.textContent=local(journey.reason);el.menuLink.href=`menu.html#${journey.companion.category}`;renderDone()}
function renderDone(){const done=current&&discovered.has(current.id);el.done.textContent=done?copy[lang].discovered:copy[lang].markDiscovered;el.done.classList.toggle("is-done",Boolean(done));el.done.disabled=Boolean(done)}
function renderContext(){el.time.textContent=`🕒 ${copy[lang].time[time]}`;const icon=weather==="hot"?"☀️":weather==="rain"?"🌧️":weather==="cool"?"🧥":weather==="mild"?"🌤️":"○";el.weather.textContent=`${icon} ${copy[lang].weather[weather]}`}
function translate(){document.documentElement.lang=lang;document.title=lang==="tr"?"Roby's Taste Journey | Menü Keşfi":lang==="ru"?"Roby's Taste Journey | Знакомство с меню":"Roby's Taste Journey | Discover the Menu";document.querySelectorAll("[data-copy]").forEach(node=>{const key=node.dataset.copy;if(copy[lang][key])node.textContent=copy[lang][key]});el.langs.forEach(button=>{const active=button.dataset.lang===lang;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active))});renderContext();renderStage();if(current)renderJourney(current)}
async function loadWeather(){const url=new URL("https://api.open-meteo.com/v1/forecast");url.searchParams.set("latitude","36.2667");url.searchParams.set("longitude","32.3167");url.searchParams.set("current","temperature_2m,precipitation,weather_code");url.searchParams.set("timezone","Europe/Istanbul");url.searchParams.set("forecast_days","1");let nextWeather="unavailable";try{const response=await fetch(url,{method:"GET",mode:"cors",credentials:"omit"});if(!response.ok)throw new Error();const data=await response.json(),temperature=Number(data.current?.temperature_2m),rain=Number(data.current?.precipitation),code=Number(data.current?.weather_code);nextWeather=(Number.isFinite(rain)&&rain>0)||(Number.isFinite(code)&&code>=51)?"rain":Number.isFinite(temperature)&&temperature>=27?"hot":Number.isFinite(temperature)&&temperature<=17?"cool":Number.isFinite(temperature)?"mild":"unavailable"}catch{}if(userInteracted)return;weather=nextWeather;renderContext();choose();renderJourney(candidates[0])}
el.langs.forEach(button=>button.addEventListener("click",()=>{const next=button.dataset.lang;if(!supportedLanguages.includes(next))return;lang=next;write(S.language,lang);translate()}));el.next.addEventListener("click",()=>{userInteracted=true;if(!candidates.length)return;candidateIndex=(candidateIndex+1)%candidates.length;renderJourney(candidates[candidateIndex])});el.done.addEventListener("click",()=>{userInteracted=true;if(!current||discovered.has(current.id))return;discovered.add(current.id);write(S.discovered,JSON.stringify([...discovered]));renderDone()});document.querySelector("#current-year").textContent=String(new Date().getFullYear());translate();choose();renderJourney(candidates[0]);loadWeather();

const journeyDeck=document.querySelector("#journey-deck");
const pairingOffers=menuCategories.find(category=>category.id==="pairing-offers")?.items??[];
function pairingOffer(journeyId){return pairingOffers.find(item=>item.journeyId===journeyId)??null}
function deckCandidates(){return candidates.map(journey=>({journey,offer:pairingOffer(journey.id)})).filter(entry=>entry.offer&&entry.offer.image&&Number.isFinite(entry.offer.price))}
function selectDeckJourney(journeyId,button){const targetIndex=candidates.findIndex(journey=>journey.id===journeyId);if(targetIndex<0)return;if(current?.id!==journeyId){userInteracted=true;const steps=(targetIndex-candidateIndex+candidates.length)%candidates.length;for(let step=0;step<steps;step+=1)el.next.click()}document.querySelector("#pairing-card")?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"center"});button?.focus({preventScroll:true})}
function renderJourneyDeck(){if(!journeyDeck)return;const entries=deckCandidates();if(entries.length!==2){journeyDeck.hidden=true;journeyDeck.replaceChildren();return}const fragment=document.createDocumentFragment();entries.forEach(({journey,offer},index)=>{const item=document.createElement("article");item.className="journey-deck-item";item.dataset.journeyId=journey.id;item.dataset.deckIndex=String(index);item.setAttribute("role","listitem");const button=document.createElement("button");button.type="button";button.className="journey-deck-card";button.dataset.journeySelect=journey.id;const selected=current?.id===journey.id;button.setAttribute("aria-pressed",String(selected));button.setAttribute("aria-label",`${local(offer.name)} · ${price(offer.price)}`);const image=document.createElement("img");image.src=offer.image;image.alt=local(offer.imageAlt??offer.name);image.loading=index===0?"eager":"lazy";image.decoding="async";image.width=1024;image.height=1024;const shade=document.createElement("span");shade.className="journey-deck-shade";shade.setAttribute("aria-hidden","true");const copyWrap=document.createElement("span");copyWrap.className="journey-deck-copy";const kicker=document.createElement("span");kicker.className="journey-deck-kicker";kicker.textContent=copy[lang].pairingKicker;const title=document.createElement("strong");title.textContent=local(offer.name);const reason=document.createElement("span");reason.className="journey-deck-reason";reason.textContent=local(journey.reason);const footer=document.createElement("span");footer.className="journey-deck-footer";const cost=document.createElement("b");cost.textContent=price(offer.price);const state=document.createElement("span");state.className="journey-deck-state";state.textContent=selected?(lang==="ru"?"Выбрано":lang==="en"?"Selected":"Seçildi"):(lang==="ru"?"Выбрать":lang==="en"?"Choose":"Seç");footer.append(cost,state);copyWrap.append(kicker,title,reason,footer);button.append(image,shade,copyWrap);button.addEventListener("click",()=>selectDeckJourney(journey.id,button));item.append(button);fragment.append(item)});journeyDeck.replaceChildren(fragment);journeyDeck.hidden=false}
if(journeyDeck){new MutationObserver(renderJourneyDeck).observe(el.products,{attributes:true,attributeFilter:["data-pairing-id"]});new MutationObserver(renderJourneyDeck).observe(document.documentElement,{attributes:true,attributeFilter:["lang"]});renderJourneyDeck()}
