#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SCHEMA='ltp-project-trace.v1';
const registryText=readFileSync(fileURLToPath(new URL('../docs/contracts/ltp-critical-actions.v0.1.json',import.meta.url)),'utf8');
const registry=JSON.parse(registryText);
if(registry.contract!=='LTP-CRITICAL-ACTIONS-001'||registry.version!=='0.1'||!Array.isArray(registry.actions)||!registry.actions.length) throw new Error('Invalid canonical critical-action registry');
const critical=new Set(registry.actions), registryDigest=createHash('sha256').update(registryText).digest('hex');
const terminal=new Set(['BLOCK','DENY','HOLD']), decisions=new Set(['ALLOW','BLOCK','DENY','HOLD','OBSERVE']), baselines=new Set(['MATCH','DRIFT']), sources=new Set(['SYSTEM','HUMAN','CI','REPOSITORY','WEB','TOOL','MODEL']);
const required=['schema_version','trace_id','run_id','agent_id','event_id','sequence','timestamp','source','action','decision','baseline_status','constraint_digest','source_payload_digest','redacted_payload_digest','previous_event_digest','parent_event_id','authorization_event_id','critical_action','protected_effect','authorized','committed','resume','trace_complete','redaction_status','event_digest'];
const allowed=new Set([...required,'payload','metadata']);
const hex=v=>typeof v==='string'&&/^[0-9a-f]{64}$/.test(v);
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort((a,b)=>a.localeCompare(b,'en')).map(k=>[k,stable(v[k])])):v;
export const canonicalize=v=>JSON.stringify(stable(v));
export const sha256=v=>createHash('sha256').update(v).digest('hex');
export const digestEvent=e=>{const c={...e};delete c.event_digest;return sha256(canonicalize(c));};
const problem=(code,message,event=null,severity='ERROR')=>({code,severity,message,event_id:event?.event_id??null,sequence:event?.sequence??null});

function parse(text){
 const t=text.trim(); if(!t)return{events:[],issues:[problem('LTP.PARSE.EMPTY','Trace is empty')]};
 if(t.startsWith('['))return{events:[],issues:[problem('LTP.PARSE.JSON_ARRAY','Canonical trace must be JSONL, not a JSON array')]};
 const events=[],issues=[];
 for(const [i,line] of text.split(/\r?\n/).entries())if(line.trim())try{const v=JSON.parse(line);if(!v||Array.isArray(v)||typeof v!=='object')issues.push(problem('LTP.PARSE.OBJECT_REQUIRED',`Line ${i+1} is not a JSON object`));else events.push(v);}catch(e){issues.push(problem('LTP.PARSE.MALFORMED_JSONL',`Line ${i+1}: ${e.message}`));}
 return{events,issues};
}
function sensitive(v,path='$',out=[]){
 if(typeof v==='string'){if([/-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----/,/\bgh[pousr]_[A-Za-z0-9]{30,}\b/,/\bgithub_pat_[A-Za-z0-9_]{60,}\b/,/\bsk-(?:proj-)?[A-Za-z0-9_-]{20,}\b/,/\bAKIA[0-9A-Z]{16}\b/,/\bxox[baprs]-[0-9A-Za-z-]{20,}\b/,/\bsk_(?:live|test)_[0-9A-Za-z]{16,}\b/,/\b(?:password|passwd|client_secret|access_token|auth_token|api_key)\s*[:=]\s*[^\s]{8,}/i].some(r=>r.test(v)))out.push(path);return out;}
 if(Array.isArray(v)){v.forEach((x,i)=>sensitive(x,`${path}[${i}]`,out));return out;}
 if(v&&typeof v==='object')for(const [k,x] of Object.entries(v)){if(/^(?:password|passwd|client_secret|access_token|auth_token|api_key|raw_model_output|private_content)$/i.test(k))out.push(`${path}.${k}`);sensitive(x,`${path}.${k}`,out);}return out;
}
function shape(e,strict){
 const x=[];for(const f of required)if(!(f in e))x.push(problem('LTP.SCHEMA.MISSING_FIELD',`Missing field: ${f}`,e));
 if(e.schema_version!==SCHEMA)x.push(problem('LTP.SCHEMA.UNSUPPORTED_VERSION',`Unsupported schema version: ${e.schema_version}`,e));
 if(!Number.isInteger(e.sequence)||e.sequence<1)x.push(problem('LTP.SCHEMA.INVALID_SEQUENCE','sequence must be a positive integer',e));
 for(const f of ['trace_id','run_id','agent_id','event_id','action'])if(typeof e[f]!=='string'||!e[f])x.push(problem('LTP.SCHEMA.INVALID_IDENTITY',`${f} must be a non-empty string`,e));
 if(!sources.has(e.source))x.push(problem('LTP.SCHEMA.INVALID_SOURCE',`Invalid source: ${e.source}`,e));if(!decisions.has(e.decision))x.push(problem('LTP.SCHEMA.INVALID_DECISION',`Invalid decision: ${e.decision}`,e));if(!baselines.has(e.baseline_status))x.push(problem('LTP.SCHEMA.INVALID_BASELINE',`Invalid baseline_status: ${e.baseline_status}`,e));
 if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z$/.test(e.timestamp)||Number.isNaN(Date.parse(e.timestamp)))x.push(problem('LTP.SCHEMA.INVALID_TIMESTAMP',`Invalid RFC3339 UTC timestamp: ${e.timestamp}`,e));
 for(const f of ['constraint_digest','source_payload_digest','redacted_payload_digest','event_digest'])if(!hex(e[f]))x.push(problem('LTP.SCHEMA.INVALID_DIGEST',`${f} must be lowercase SHA-256`,e));if(e.previous_event_digest!==null&&!hex(e.previous_event_digest))x.push(problem('LTP.SCHEMA.INVALID_DIGEST','previous_event_digest must be null or lowercase SHA-256',e));
 for(const f of ['parent_event_id','authorization_event_id'])if(e[f]!==null&&(typeof e[f]!=='string'||!e[f]))x.push(problem('LTP.SCHEMA.INVALID_REFERENCE',`${f} must be null or a non-empty string`,e));for(const f of ['critical_action','protected_effect','authorized','committed','resume','trace_complete'])if(typeof e[f]!=='boolean')x.push(problem('LTP.SCHEMA.INVALID_BOOLEAN',`${f} must be boolean`,e));
 if(e.redaction_status!=='clean')x.push(problem('LTP.PRIVACY.REDACTION_NOT_CLEAN','redaction_status must be clean',e));const leaks=sensitive(e.payload??null);if(leaks.length)x.push(problem('LTP.PRIVACY.SENSITIVE_DATA',`Sensitive data found at ${leaks.join(', ')}`,e));if(strict){const u=Object.keys(e).filter(k=>!allowed.has(k));if(u.length)x.push(problem('LTP.SCHEMA.UNKNOWN_FIELD',`Unknown fields: ${u.join(', ')}`,e));}return x;
}
function verdict(issues,events){if(issues.some(i=>i.severity==='ERROR'))return issues.every(i=>i.code.startsWith('LTP.PARSE')||i.code.startsWith('LTP.RUNTIME'))?'INCONCLUSIVE':'REJECTED';return events.some(e=>e.baseline_status==='DRIFT')?'DRIFT':'ADMISSIBLE';}
function report(events,issues,v){
 const has=p=>issues.some(i=>i.code.startsWith(p)), action=issues.some(i=>i.code.startsWith('LTP.ACTION')||i.code==='AGENTS.CRIT.WEB_DIRECT');
 return{contract:'LTP-PROJECT-AUDIT-001',schema_version:SCHEMA,critical_action_registry_digest:registryDigest,verdict:v,exit_code:['ADMISSIBLE','DRIFT'].includes(v)?0:2,trace_integrity:has('LTP.INTEGRITY')||has('LTP.SCHEMA')||has('LTP.PARSE')?'invalid':'verified',identity_binding:has('LTP.IDENTITY')?'invalid':events.length?'ok':'unverified',replay_determinism:events.length?'ok':'unverified',action_boundaries:action?'invalid':events.length?'ok':'unverified',privacy:has('LTP.PRIVACY')?'invalid':events.length?'ok':'unverified',trace_complete:Boolean(events.length&&events.at(-1)?.trace_complete),event_count:events.length,trace_id:events[0]?.trace_id??null,run_id:events[0]?.run_id??null,agent_id:events[0]?.agent_id??null,trace_digest:events.length?sha256(events.map(e=>`${canonicalize(e)}\n`).join('')):null,model_calls:events.filter(e=>e.source==='MODEL').length,tool_calls:events.filter(e=>e.source==='TOOL').length,effect_calls:events.filter(e=>e.protected_effect).length,issues:issues.sort((a,b)=>(a.sequence??1e15)-(b.sequence??1e15)||a.code.localeCompare(b.code,'en'))};
}
export function inspectTraceText(text,{strict=false}={}){
 const p=parse(text),events=p.events,issues=[...p.issues];if(!events.length)return report(events,issues,verdict(issues,events));
 const ids=new Map(),seq=new Set(),identity={trace_id:events[0].trace_id,run_id:events[0].run_id,agent_id:events[0].agent_id,constraint_digest:events[0].constraint_digest};let lastTime=-Infinity,stop=null;
 for(const [i,e] of events.entries()){
  issues.push(...shape(e,strict));const pd=sha256(canonicalize(e.payload??null));if(e.redacted_payload_digest!==pd)issues.push(problem('LTP.INTEGRITY.REDACTED_PAYLOAD_DIGEST',`redacted_payload_digest mismatch: expected ${pd}`,e));if(e.redaction_status==='clean'&&e.source_payload_digest!==e.redacted_payload_digest)issues.push(problem('LTP.INTEGRITY.SOURCE_PAYLOAD_DIGEST','clean payload requires source_payload_digest to equal redacted_payload_digest',e));
  if(e.critical_action!==critical.has(e.action))issues.push(problem('LTP.ACTION.REGISTRY_MISMATCH',`critical_action=${e.critical_action} does not match canonical registry for ${e.action}`,e));if(ids.has(e.event_id))issues.push(problem(canonicalize(ids.get(e.event_id))===canonicalize(e)?'LTP.INTEGRITY.DUPLICATE_EVENT':'LTP.INTEGRITY.CONFLICTING_DUPLICATE_ID',`Duplicate event_id: ${e.event_id}`,e));else ids.set(e.event_id,e);
  if(seq.has(e.sequence))issues.push(problem('LTP.INTEGRITY.DUPLICATE_SEQUENCE',`Duplicate sequence: ${e.sequence}`,e));seq.add(e.sequence);if(e.sequence!==i+1)issues.push(problem('LTP.INTEGRITY.SEQUENCE_GAP_OR_REORDER',`Expected sequence ${i+1}, got ${e.sequence}`,e));if(e.trace_id!==identity.trace_id||e.run_id!==identity.run_id||e.agent_id!==identity.agent_id)issues.push(problem('LTP.IDENTITY.CONTINUITY','trace/run/agent identity changed',e));if(e.constraint_digest!==identity.constraint_digest)issues.push(problem('LTP.CONSTRAINT.CONTINUITY','constraint_digest changed',e));
  const ms=Date.parse(e.timestamp);if(Number.isFinite(ms)){if(ms<lastTime)issues.push(problem('LTP.INTEGRITY.TIMESTAMP_ORDER','timestamp moved backwards',e));lastTime=ms;}const expected=digestEvent(e);if(e.event_digest!==expected)issues.push(problem('LTP.INTEGRITY.EVENT_DIGEST',`event_digest mismatch: expected ${expected}`,e));
  if(i===0){if(e.previous_event_digest!==null)issues.push(problem('LTP.INTEGRITY.GENESIS_PREVIOUS','First event previous_event_digest must be null',e));if(e.parent_event_id!==null)issues.push(problem('LTP.INTEGRITY.GENESIS_PARENT','First event parent_event_id must be null',e));}else{const prev=events[i-1];if(e.previous_event_digest!==prev.event_digest)issues.push(problem('LTP.INTEGRITY.PREVIOUS_HASH',`previous_event_digest does not match ${prev.event_id}`,e));if(e.parent_event_id!==null){const pi=events.findIndex(x=>x.event_id===e.parent_event_id);if(pi<0||pi>=i)issues.push(problem('LTP.INTEGRITY.PARENT_BINDING',`parent_event_id must reference an earlier event: ${e.parent_event_id}`,e));}}
  if(stop&&(e.protected_effect||e.resume))issues.push(problem('LTP.ACTION.EXECUTION_AFTER_NON_ALLOW',`${e.protected_effect?'Protected effect':'Resume'} after ${stop.decision} at ${stop.event_id}`,e));if(terminal.has(e.decision))stop=e;
  if(e.protected_effect){if(e.decision!=='ALLOW'||!e.authorized||!e.committed)issues.push(problem('LTP.ACTION.BOUNDARY','Protected effect requires ALLOW, authorized=true and committed=true',e));if(!e.authorization_event_id)issues.push(problem('LTP.ACTION.AUTHORIZATION_MISSING','Protected effect has no authorization_event_id',e));else{const ai=events.findIndex(x=>x.event_id===e.authorization_event_id),a=events[ai];if(!a||ai>=i||a.decision!=='ALLOW'||a.action!=='authorize')issues.push(problem('LTP.ACTION.AUTHORIZATION_INVALID','authorization_event_id must reference an earlier ALLOW authorize event',e));}}else if(e.authorization_event_id!==null)issues.push(problem('LTP.ACTION.UNEXPECTED_AUTHORIZATION_REFERENCE','Non-effect event must not set authorization_event_id',e));if(e.source==='WEB'&&e.critical_action&&e.protected_effect)issues.push(problem('AGENTS.CRIT.WEB_DIRECT','Untrusted WEB context directly triggered a critical protected effect',e));
 }
 if(!events.at(-1)?.trace_complete)issues.push(problem('LTP.COMPLETENESS.PARTIAL_TRACE','Final event must set trace_complete=true',events.at(-1)));if(events.slice(0,-1).some(e=>e.trace_complete))issues.push(problem('LTP.COMPLETENESS.EARLY_COMPLETE','Only the final event may set trace_complete=true'));
 return report(events,issues,verdict(issues,events));
}
export function replayTraceText(text,opts={}){const r=inspectTraceText(text,opts),events=parse(text).events;return{contract:r.contract,schema_version:r.schema_version,critical_action_registry_digest:r.critical_action_registry_digest,verdict:r.verdict,trace_digest:r.trace_digest,event_count:r.event_count,trace_id:r.trace_id,run_id:r.run_id,agent_id:r.agent_id,state_path:events.map(e=>({sequence:e.sequence,event_id:e.event_id,action:e.action,decision:e.decision,baseline_status:e.baseline_status,protected_effect:e.protected_effect})),issue_codes:r.issues.map(i=>i.code)};}
export function explainTraceText(text,at,opts={}){const r=inspectTraceText(text,opts),events=parse(text).events,e=events.find(x=>x.event_id===at||String(x.sequence)===String(at));return{contract:r.contract,verdict:r.verdict,at,event:e??null,previous_event:e?events[e.sequence-2]??null:null,issues:r.issues.filter(i=>i.event_id===e?.event_id||i.sequence===e?.sequence)};}
function cli(args){const [command,...rest]=args,o={command,strict:false,quiet:false,format:'json',color:'never',input:null,at:null};for(let i=0;i<rest.length;i++){const a=rest[i];if(a==='--strict')o.strict=true;else if(a==='--quiet')o.quiet=true;else if(['--format','--color','--input','--at'].includes(a))o[a.slice(2)]=rest[++i];else throw new Error(`Unknown argument: ${a}`);}if(!new Set(['trace','replay','explain']).has(command))throw new Error(`Unknown command: ${command}`);if(!o.input)throw new Error('--input is required');if(command==='explain'&&!o.at)throw new Error('--at is required for explain');if(o.format!=='json')throw new Error('Only --format json is supported');return o;}
function run(){try{const o=cli(process.argv.slice(2)),text=readFileSync(o.input,'utf8'),v=o.command==='trace'?inspectTraceText(text,o):o.command==='replay'?replayTraceText(text,o):explainTraceText(text,o.at,o);process.stdout.write(`${canonicalize(v)}\n`);process.exitCode=o.command==='explain'?(v.event?0:2):['ADMISSIBLE','DRIFT'].includes(v.verdict)?0:2;}catch(e){const v={contract:'LTP-PROJECT-AUDIT-001',verdict:'INCONCLUSIVE',exit_code:2,issues:[problem('LTP.RUNTIME.FAILURE',e instanceof Error?e.message:String(e))]};process.stderr.write(`${canonicalize(v)}\n`);process.exitCode=2;}}
if(process.argv[1]&&fileURLToPath(import.meta.url)===process.argv[1])run();
